### PR TITLE
Fix $SCP_DEST variable name in openssh-server test

### PR DESCRIPTION
**Pull request by bbotti**
Signed-off-by: Ben Botti <bbotti@mvista.com>

### CODE REVIEW

**Comment by bbotti** [comment]
Fixes this error:

not ok 2 bat-openssh-server: copy keys for another user
# (in test file bat-openssh-server.t, line 34)
#   `cat $Newkey.pub > $SCP_DEST/.ssh/authorized_keys' failed
# /tmp/bats.1145.src: line 34: /home/dummy/.ssh/authorized_keys: No such file or directory
Password:

**Comment by bbotti** [comment]
This adds a run.sh script to detect installed bundles and run all applicable tests.  Thanks to sofar for the base code!

**Comment by ahkok** [comment]
The first commit is great, but the second one conflicts, so, can you remove the second commit from your PR branch?

**Comment by bbotti** [comment]
Ok, I removed the second commit (run.sh) file.  Thanks!

**Comment by mbelluzzo** [comment]
Merged, thanks!

**Pull request closed without merging**
